### ISSUE TITLE
vivo x7 android 5.1.1版本安装有问题。

### ISSUE THREAD

**Issue by thebossforme** [ddnosh/AndroidQuick#3]
安装成功 无法使用。目前测试小米、红米都正常

**Comment by thebossforme** [comment]
安装后有图标 点击无反应
 java.lang.RuntimeException: Unable to start activity ComponentInfo{*包名删了}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setFitsSystemWindows(boolean)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
        at android.app.ActivityThread.access$900(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5418)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setFitsSystemWindows(boolean)' on a null object reference
        at spa.lyh.cn.statusbarlightmode.barutils.barUtils.transparencyBar(barUtils.java:59)
        at spa.lyh.cn.statusbarlightmode.helpers.immersionmode.ImmersionHelper.changeStatusBarColor(ImmersionHelper.java:47)
        at spa.lyh.cn.statusbarlightmode.helpers.immersionmode.ImmersionHelper.statusBarFitToAPP(ImmersionHelper.java:35)
        at spa.lyh.cn.statusbarlightmode.ImmersionMode.execImmersionMode(ImmersionMode.java:72)
        at la.xiong.androidquick.ui.base.QuickActivity.onCreate(QuickActivity.java:125)
        at android.app.Activity.performCreate(Activity.java:6083)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
        at android.app.ActivityThread.access$900(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5418) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by thebossforme** [comment]
华为很多型号直接崩溃- -同上

**Comment by ddnosh** [comment]
@thebossforme 这个是沉浸式状态栏兼容性的问题，后续会做兼容处理。
