### ISSUE TITLE
W/System.err: java.lang.ClassNotFoundException: com.androidwind.annotation.TagService

### ISSUE THREAD

**Issue by netgb** [ddnosh/AndroidQuick#8]
这两个问题能抽时间修改一下不？尤其是第二个，好晕，每次运行爆红字
1、------------------------------------------------------
W/System.err: java.lang.ClassNotFoundException: com.androidwind.annotation.TagService
W/System.err:     at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at com.androidwind.annotation.core.SearchEngine.init(SearchEngine.java:31)
2、------------------------------------------------------
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: sample

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: sample

**Comment by ddnosh** [comment]
第一个rebuild一下试下；
第二个我把compile全部替换了，可以update一下。

**Comment by netgb** [comment]
新建空文件夹重新检出项目也是一样的情况，我这边是用AS3.4.2版本去运行项目，
貌似两个问题都还存在，你能把gradle插件也更新到3.4.2版本吗？
第一个问题，这个com.androidwind.annotation.TagService还是找不到
@ddnosh

**Comment by netgb** [comment]
![图片](https://user-images.githubusercontent.com/10653441/66270027-6e45bc80-e881-11e9-80c1-8a007280a735.png)

**Comment by netgb** [comment]
![图片](https://user-images.githubusercontent.com/10653441/66270043-9c2b0100-e881-11e9-9fa6-a65f8cf6a75b.png)
